[package]
name = 'wasmer/adminer'
version = '0.1.0'
description = 'Adminer - Database management in a single PHP file'

[dependencies]
"php/php" = "=8.3.402"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "localhost:8080"]
