[package]
name = 'wasmer/adminer'
version = '0.3.0'
description = 'Adminer - Database management in a single PHP file'
entrypoint = "run"
readme = "README.md"
repository = "https://github.com/wasmerio/adminer"

[dependencies]
"php/php-eh" = "=8.3.404-beta.8"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php-eh:php"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-c", "/app/php.ini", "-t", "/app", "-S", "localhost:8080"]
