[package]
name = 'wasmer/adminer'
version = '0.1.0'
description = 'Adminer - Database management in a single PHP file'
entrypoint = "run"

[dependencies]
"php/php" = "8"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-c", "/app/php.ini", "-t", "/app", "-S", "localhost:8080"]
